class SemanticID{
    static String MAIN_SCREEN_FAVORITE_TAB = 'MAIN_SCREEN_FAVORITE_TAB';
    static String MAIN_SCREEN_SEARCH_TAB = 'MAIN_SCREEN_SEARCH_TAB';
    static String SEARCH_SCREEN_SEARCH_BUTTON = 'MAIN_SCREEN_SEARCH_TAB';
    static String SEARCH_SCREEN_INPUT_FORM = 'MAIN_SCREEN_SEARCH_TAB';
    static String SEARCH_SCREEN_LIST_ITEM = 'SEARCH_SCREEN_LIST_ITEM';
    static String SEARCH_SCREEN_LIST_ITEM_IMAGE = 'SEARCH_SCREEN_LIST_ITEM_IMAGE';
    static String SEARCH_SCREEN_LIST_ITEM_FAVORITE = 'SEARCH_SCREEN_LIST_ITEM_FAVORITE';
}